language: objective-c
osx_image: xcode10.3
xcode_workspace: SwiftUtilBiP.xcworkspace # path to your xcodeproj folder
xcode_scheme: BiPiOS
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone X
before_install:
    - pod install
after_success:
    - gem install jazzy
    - make docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master
