language: objective-c
osx_image: xcode10.1
xcode_workspace: SwiftUtilBiP.xcodeproj # path to your xcodeproj folder
xcode_scheme: BiPMacOS
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
#before_install:
#    - pod install
after_success:
    - gem install jazzy
    - make docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master
