name: XCTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Run tests iOS
      run: xcodebuild clean test -workspace SwiftUtilBiP.xcworkspace -scheme BiPiOS -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Run tests macOS
      run: xcodebuild clean test -workspace SwiftUtilBiP.xcworkspace -scheme BiPmacOS -destination "platform=macOS"
